apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-secret
  labels:
    app: external-sso
spec:
  realmSelector:
    matchLabels:
      app: external-sso
  roles:
    - name: some-client-role
  client:
    clientId: client-secret
    secret: client-secret
    clientAuthenticatorType: client-secret
    protocol: openid-connect