apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator-legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak-operator-legacy
  template:
    metadata:
      labels:
        name: keycloak-operator-legacy
    spec:
      serviceAccountName: keycloak-operator-legacy
      containers:
        - name: keycloak-operator-legacy
          image: quay.io/keycloak/keycloak-operator:19.0.1-legacy
          command:
          - keycloak-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keycloak-operator-legacy"
